name: "Sydney Haskell"
description: "Sydney Haskell is for all programmers either interested in or experienced with the Haskell programming language. Our events center around the community, learning via pairing, participating in open-source sprints, shipping documentation, and software. We want to build a community of Haskell developers in the Sydney area that can share knowledge, projects, and experience, and to generally foster and encourage strongly typed functional programming, in all languages, all settings, and all industries."

markdown: kramdown

gems: [jekyll-paginate]
exclude: [Gemfile, Gemfile.lock, CNAME, Readme.md]

footer-links:
  github: sydneyhaskell

# google_analytics:
url: http://sydneyhaskell.org


kramdown:
  input: GFM
  hard_wrap: false

paginate: 4
paginate_path: "/blog/page:num/"

permalink: /blog/:year/:month/:day/:title.html
