name: "NY Haskell Users Group"
description: "The NY Haskell Users Group is for all programmers either interested in or experienced with the Haskell programming language. We want to build a community of Haskell developers in the New York area that can share knowledge, projects, and experience, and to generally foster and encourage strongly typed functional programming, in all languages, all settings, and all industries. Our events center around talks, but we have also hosted social hours, code workshops, and a hackathon. Regular meetings are on the fourth wednesday of each month."

markdown: kramdown

exclude: [Gemfile, Gemfile.lock, CNAME, Readme.md]

footer-links:
  github: ny-haskell

# google_analytics:

url: http://ny-haskell.org
